--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/psy/.config/wallpaper/forest_fox.jpg"

-- Special
background="#0b0f18"
foreground="#e0dcd0"
cursor="#e0dcd0"

-- Colors
color0="#0b0f18"
color1="#A94F34"
color2="#966859"
color3="#A09473"
color4="#DBAA54"
color5="#728082"
color6="#A0A394"
color7="#e0dcd0"
color8="#9c9a91"
color9="#A94F34"
color10="#966859"
color11="#A09473"
color12="#DBAA54"
color13="#728082"
color14="#A0A394"
color15="#e0dcd0"
