# Shell variables
# Generated by 'wal'
wallpaper='/home/psy/.config/wallpaper/forest_fox.jpg'

# Special
background='#0b0f18'
foreground='#e0dcd0'
cursor='#e0dcd0'

# Colors
color0='#0b0f18'
color1='#A94F34'
color2='#966859'
color3='#A09473'
color4='#DBAA54'
color5='#728082'
color6='#A0A394'
color7='#e0dcd0'
color8='#9c9a91'
color9='#A94F34'
color10='#966859'
color11='#A09473'
color12='#DBAA54'
color13='#728082'
color14='#A0A394'
color15='#e0dcd0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
